# Is performed before the scripts in the stages step
before_script:  
  - source /etc/profile

# Defines stages which are to be executed
stages:  
  - build

# Stage "build"
run-build:  
  stage: build
  script:
    - git submodule init && git submodule update
    - cd qtinyaes && git submodule init && git submodule update && cd ..
    - debuild clean
    - echo "y" | debuild -us -uc
    - mkdir build
    - mv ../openforti*.deb build/

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*
