# Is performed before the scripts in the stages step
before_script:  
  - source /etc/profile

# Defines stages which are to be executed
stages:  
  - build

# Stage "build"
run-build:  
  stage: build
  script:
    - apt-get install -y libssl-dev 
    - autoreconf -fvi
    - debuild -us -uc
    - mkdir build
    - mv ../openforti*.deb build/

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*